packages:
  - 'packages/*'
  - 'apps/*'
  - 'internal/*'
  - 'internal/lint-configs/*'
catalog:
  '@iconify/json': '^2.2.281'
  '@iconify/tailwind': '^1.2.0'
  '@manypkg/get-packages': '^2.2.2'
  '@tailwindcss/typography': '^0.5.15'
  '@types/postcss-import': '^14.0.3'
  'autoprefixer': '^10.4.20'
  'postcss': '^8.4.49'
  'postcss-import': '^16.1.0'
  'postcss-preset-env': '^10.1.1'
  'tailwindcss': '^3.4.16'
  'tailwindcss-animate': '^1.0.7'
  'prettier': '^3.4.2'
  'prettier-plugin-tailwindcss': '^0.6.9'
